_commit: a046d85
_src_path: https://github.com/cvasilatos/python-template-project.git
description: The ICSClone progression
project_name: ICSD Surrogate
project_slug: icsd_surrogate
python_minor_version: 3.14.3
python_target_version: '314'
python_version: '3.14'
