"""Configuration constants for Proteus protocol fuzzer."""

DEFAULT_HOST = "localhost"
DEFAULT_PORT = 5020
DEFAULT_TIMEOUT = 1.0
VALIDATION_TIMEOUT = 0.01

DEFAULT_MUTATION_SAMPLE_SIZE = 1000
FUZZABLE_THRESHOLD = 50
CONSTRAINED_THRESHOLD = 10

INVALID_RESPONSE_PREFIX = "0000"
ERROR_CODE_SUFFIX = "04"
